// Code generated by qtc from "templates.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line templates/templates.qtpl:1
package templates

//line templates/templates.qtpl:1
import "snac/Database"

//line templates/templates.qtpl:3
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line templates/templates.qtpl:3
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line templates/templates.qtpl:3
func StreamTags(qw422016 *qt422016.Writer, tags []Database.TagOverview) {
//line templates/templates.qtpl:3
	qw422016.N().S(`
	`)
//line templates/templates.qtpl:4
	for _, tag := range tags {
//line templates/templates.qtpl:4
		qw422016.N().S(`
		<input type="radio" id="tag-`)
//line templates/templates.qtpl:5
		qw422016.E().S(tag.Name)
//line templates/templates.qtpl:5
		qw422016.N().S(`" name="tag"/>
        <div class="tag" data-tag="`)
//line templates/templates.qtpl:6
		qw422016.E().S(tag.Name)
//line templates/templates.qtpl:6
		qw422016.N().S(`" onclick='unrollTag(this); console.log("dikka")'><label for="tag-`)
//line templates/templates.qtpl:6
		qw422016.E().S(tag.Name)
//line templates/templates.qtpl:6
		qw422016.N().S(`"><span>`)
//line templates/templates.qtpl:6
		qw422016.E().S(tag.Name)
//line templates/templates.qtpl:6
		qw422016.N().S(` (`)
//line templates/templates.qtpl:6
		qw422016.N().D(tag.Count)
//line templates/templates.qtpl:6
		qw422016.N().S(`)<span>祈</span></span></label>
            <ul style="min-height: calc(`)
//line templates/templates.qtpl:7
		qw422016.N().D(tag.Count)
//line templates/templates.qtpl:7
		qw422016.N().S(` * (1em + 8px));"></ul>
        </div>
	`)
//line templates/templates.qtpl:9
	}
//line templates/templates.qtpl:9
	qw422016.N().S(`
`)
//line templates/templates.qtpl:10
}

//line templates/templates.qtpl:10
func WriteTags(qq422016 qtio422016.Writer, tags []Database.TagOverview) {
//line templates/templates.qtpl:10
	qw422016 := qt422016.AcquireWriter(qq422016)
//line templates/templates.qtpl:10
	StreamTags(qw422016, tags)
//line templates/templates.qtpl:10
	qt422016.ReleaseWriter(qw422016)
//line templates/templates.qtpl:10
}

//line templates/templates.qtpl:10
func Tags(tags []Database.TagOverview) string {
//line templates/templates.qtpl:10
	qb422016 := qt422016.AcquireByteBuffer()
//line templates/templates.qtpl:10
	WriteTags(qb422016, tags)
//line templates/templates.qtpl:10
	qs422016 := string(qb422016.B)
//line templates/templates.qtpl:10
	qt422016.ReleaseByteBuffer(qb422016)
//line templates/templates.qtpl:10
	return qs422016
//line templates/templates.qtpl:10
}

//line templates/templates.qtpl:12
func StreamTagContent(qw422016 *qt422016.Writer, snippets []Database.SnippetOverview) {
//line templates/templates.qtpl:12
	qw422016.N().S(`
	`)
//line templates/templates.qtpl:13
	for _, snippet := range snippets {
//line templates/templates.qtpl:13
		qw422016.N().S(`
		<li data-id="`)
//line templates/templates.qtpl:14
		qw422016.E().S(snippet.Id)
//line templates/templates.qtpl:14
		qw422016.N().S(`" onclick="event.stopPropagation(); Editor.openRemoteSnippet('`)
//line templates/templates.qtpl:14
		qw422016.E().S(snippet.Id)
//line templates/templates.qtpl:14
		qw422016.N().S(`')"><span>`)
//line templates/templates.qtpl:14
		qw422016.E().S(snippet.Id)
//line templates/templates.qtpl:14
		qw422016.N().S(`</span>`)
//line templates/templates.qtpl:14
		qw422016.E().S(snippet.Title)
//line templates/templates.qtpl:14
		qw422016.N().S(`</li>
	`)
//line templates/templates.qtpl:15
	}
//line templates/templates.qtpl:15
	qw422016.N().S(`
`)
//line templates/templates.qtpl:16
}

//line templates/templates.qtpl:16
func WriteTagContent(qq422016 qtio422016.Writer, snippets []Database.SnippetOverview) {
//line templates/templates.qtpl:16
	qw422016 := qt422016.AcquireWriter(qq422016)
//line templates/templates.qtpl:16
	StreamTagContent(qw422016, snippets)
//line templates/templates.qtpl:16
	qt422016.ReleaseWriter(qw422016)
//line templates/templates.qtpl:16
}

//line templates/templates.qtpl:16
func TagContent(snippets []Database.SnippetOverview) string {
//line templates/templates.qtpl:16
	qb422016 := qt422016.AcquireByteBuffer()
//line templates/templates.qtpl:16
	WriteTagContent(qb422016, snippets)
//line templates/templates.qtpl:16
	qs422016 := string(qb422016.B)
//line templates/templates.qtpl:16
	qt422016.ReleaseByteBuffer(qb422016)
//line templates/templates.qtpl:16
	return qs422016
//line templates/templates.qtpl:16
}
